(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
	(begin (set! balance (- balance amount))
	       balance)
	"Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount)))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
	  ((eq? m 'deposit) deposit)
	  (else (error "unknown request: MAKE-ACCOUNT" m))))
  (lambda (try-pass m)
    (if
     (eq? password try-pass)
     (dispatch m)
     (lambda (x)
       "Incorrect password"))))
