(define (make-account balance password)
  (let ((attempts 0))
    (define (withdraw amount)
      (if (>= balance amount)
	  (begin (set! balance (- balance amount))
		 balance)
	  "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount)))
    (define (dispatch m)
      (cond ((eq? m 'withdraw) withdraw)
	    ((eq? m 'deposit) deposit)
	    (else (error "unknown request: MAKE-ACCOUNT" m))))
    (lambda (try-pass m)
      (if (> attempts 6)
	  (call-the-cops)
	  (if (eq? password try-pass)
	      (begin
		(set! attempts 0)
		(dispatch m))
	      (begin
		(set! attempts (+ attempts 1))
		(lambda (x)
		  "Incorrect password")))))))
