(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
	(begin (set! balance (- balance amount))
	       balance)
	"Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount)))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
	  ((eq? m 'deposit) deposit)
	  (else (error "unknown request: MAKE-ACCOUNT" m))))
  (lambda (try-pass m)
    (if (eq? m 'auth)
	(eq? password try-pass)
	(if
	 (eq? password try-pass)
	 (dispatch m)
	 (lambda (x)
	   "Incorrect password")))))

(define (make-joint orig-acc orig-pass join-pass)
  (if (orig-acc orig-pass 'auth)
      (lambda (try-pass m)
	(if (or (eq? try-pass orig-pass) (eq? try-pass join-pass))
	    (orig-acc orig-pass m)
	    (error "incorrect password"))
	)
      (error "incorrect password")))
  
